### ISSUE TITLE
Aucune actualisation des données

### ISSUE THREAD

**Issue by JeedHome44** [tux1c0/plugin-huawei4g#35]
Bonjour,

j'ai mis l'actualisation toutes les 5 minutes du plugin. Pourtant les données de transfert n temps réel ne s'actualisent pas. Ils restent avec les infos lors de la création de mon équipement. J'ai beau resauvegarder l'équipement, ca ne s'actualise pas.
je n'ai pas changé le mot de passe ni l'ip du routeur.

le plugin est mis sur Jeedom v4.

je ne vois pas le plugin huawei de le moteur de tâche. il doit y avoir un problème sur le cron.

**Comment by tux1c0** [comment]
Bonjour,

après reboot du routeur, le problème est-il toujours d'actualité ? Le routeur peut souvent bloquer une ip s'il estime qu'il est trop sollicité.
Quels sont les logs du plugin ?

Merci.

**Comment by JeedHome44** [comment]
Salut!
En fait j'ai testé d'ajouter un routage sur mon Pi pour lui dire que le Huawei est derrière un routeur TP Link et là ca marche maintenant.
Problème résolu ;)
